uploads = []
outputs = []

[[generated]]
id = "_nkskJF3mtACumQqGR1QZ"
uri = "file://frontend/public/marketing/girl-with-phone.png"
type = "image"
title = "indian woman holding phone marketing"

[[generated]]
id = "kvRmf4MUvu-U1b1rNs1i6"
uri = "file://frontend/public/marketing/boy-with-laptop.png"
type = "image"
title = "indian man with laptop happy excited"
