// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ledger-mobile-wireframe/MobileEditWireframe.tsx": () => import("../components/mockups/ledger-mobile-wireframe/MobileEditWireframe.tsx"),
  "./components/mockups/payables-redesign/Analytics.tsx": () => import("../components/mockups/payables-redesign/Analytics.tsx"),
  "./components/mockups/payables-redesign/Dashboard.tsx": () => import("../components/mockups/payables-redesign/Dashboard.tsx"),
  "./components/mockups/payables-redesign/DashboardMobile.tsx": () => import("../components/mockups/payables-redesign/DashboardMobile.tsx"),
  "./components/mockups/payables-redesign/InvoiceDetail.tsx": () => import("../components/mockups/payables-redesign/InvoiceDetail.tsx"),
  "./components/mockups/payables-redesign/Settings.tsx": () => import("../components/mockups/payables-redesign/Settings.tsx"),
  "./components/mockups/payables-redesign/Vendors.tsx": () => import("../components/mockups/payables-redesign/Vendors.tsx")
};
