import type { Metadata } from "next";

export const SITE_URL = "https://www.plyndrox.app";

export const siteConfig = {
  name: "Plyndrox AI",
  shortName: "Plyndrox",
  url: SITE_URL,
  locale: "en_US",
  defaultTitle: "Plyndrox AI — Every AI Tool You Need. Free for Everyone.",
  titleTemplate: "%s | Plyndrox AI",
  defaultDescription:
    "Plyndrox AI is the free all-in-one AI platform: personal companion, WhatsApp AI, email intelligence, invoice automation, AI hiring, regional AI, and a smart ledger — built for individuals and businesses worldwide.",
  slogan: "Every AI tool you need. Free for everyone.",
  defaultKeywords: [
    "Plyndrox",
    "Plyndrox AI",
    "Plyndrox app",
    "Plyndrox.app",
    "plyndrox ai platform",
    "free AI platform",
    "free AI tools",
    "free AI suite",
    "all in one AI",
    "all-in-one AI platform",
    "AI tools",
    "AI tools for business",
    "AI tools for free",
    "best free AI tools 2025",
    "best free AI tools 2026",
    "AI productivity tools",
    "AI suite",
    "unified AI platform",
    "AI workspace",
    "AI workspaces",
    "AI for everyone",
    "AI for small business",
    "AI for startups",
    "AI for SMBs",
    "AI for SMEs",
    "AI for enterprise",
    "AI for India",
    "AI for Indian businesses",
    "Indian AI startup",
    "Indian AI platform",
    "made in India AI",
    "Hindi AI",
    "Hinglish AI",
    "regional AI",
    "multilingual AI",
    "AI in Hindi",
    "WhatsApp AI",
    "WhatsApp business AI",
    "WhatsApp chatbot",
    "WhatsApp automation",
    "AI email assistant",
    "AI inbox",
    "Gmail AI",
    "Outlook AI",
    "AI invoice automation",
    "AI accounts payable",
    "AP automation",
    "invoice OCR AI",
    "AI for recruiters",
    "AI hiring",
    "AI ATS",
    "applicant tracking system AI",
    "AI smart ledger",
    "AI bookkeeping",
    "AI accounting",
    "satti AI",
    "Bihar AI",
    "Bhojpuri AI",
    "Maithili AI",
    "personal AI assistant",
    "personal AI companion",
    "AI chat",
    "AI chatbot",
    "free AI chatbot",
    "Ibara",
    "Ibara widget",
    "AI chat widget",
    "embeddable AI",
    "business automation",
    "workflow automation AI",
    "AI translator",
    "AI translation",
    "free translator",
    "translate Hindi to English AI",
    "ChatGPT alternative",
    "ChatGPT alternative free",
    "Gemini alternative",
    "Claude alternative",
    "Copilot alternative",
    "Perplexity alternative",
    "free AI for India",
    "AI for entrepreneurs",
    "AI for freelancers",
    "AI for agencies",
    "no credit card AI",
    "no signup AI",
    "AI without signup",
  ],
  twitterHandle: "@plyndroxai",
  organization: {
    legalName: "Plyndrox AI",
    foundingDate: "2024",
    foundingLocation: "India",
    email: "support@plyndrox.app",
    contactEmail: "support@plyndrox.app",
    pressEmail: "press@plyndrox.app",
    salesEmail: "sales@plyndrox.app",
    sameAs: [
      "https://www.plyndrox.app",
      "https://twitter.com/plyndroxai",
      "https://x.com/plyndroxai",
      "https://www.linkedin.com/company/plyndrox-ai",
      "https://github.com/plyndrox",
    ],
    knowsAbout: [
      "Artificial Intelligence",
      "Generative AI",
      "WhatsApp Business Automation",
      "Email Intelligence",
      "Accounts Payable Automation",
      "Applicant Tracking Systems",
      "AI Chatbots",
      "Indian Regional AI",
      "Smart Accounting",
      "Bookkeeping Automation",
      "Conversational AI",
      "Large Language Models",
    ],
  },
} as const;

/**
 * Massive intent-mapped keyword library, one set per product page.
 *
 * Each set is a flat string[] grouping keywords across the buyer journey:
 *   • brand & product variations
 *   • core feature & category terms
 *   • "free", pricing & alternative-to terms
 *   • specific feature/capability keywords
 *   • use-cases & verticals
 *   • audience & persona terms
 *   • competitor / comparison terms
 *   • long-tail question phrasings
 *   • regional & multilingual variations
 *
 * Spread these into a page's metadata.keywords via buildMetadata({ keywords: productKeywords.whatsapp }).
 * Combined with siteConfig.defaultKeywords, every product page ends up with
 * 150–250 unique, high-intent keywords without keyword stuffing in body copy.
 */
export const productKeywords = {
  whatsapp: [
    "WhatsApp AI",
    "WhatsApp AI bot",
    "WhatsApp AI agent",
    "WhatsApp AI chatbot",
    "WhatsApp AI assistant",
    "WhatsApp Business AI",
    "WhatsApp Business chatbot",
    "WhatsApp Business automation",
    "WhatsApp Business API free",
    "WhatsApp marketing automation",
    "WhatsApp customer support AI",
    "WhatsApp customer service automation",
    "WhatsApp lead capture",
    "WhatsApp lead generation AI",
    "WhatsApp sales automation",
    "WhatsApp drip campaign AI",
    "WhatsApp broadcast AI",
    "WhatsApp catalog AI",
    "WhatsApp ecommerce bot",
    "WhatsApp order taking bot",
    "WhatsApp booking bot",
    "WhatsApp appointment bot",
    "WhatsApp restaurant chatbot",
    "WhatsApp salon chatbot",
    "WhatsApp clinic chatbot",
    "WhatsApp real estate chatbot",
    "WhatsApp coaching chatbot",
    "WhatsApp ecommerce chatbot",
    "WhatsApp store chatbot",
    "free WhatsApp chatbot",
    "free WhatsApp automation",
    "free WhatsApp Business AI",
    "WhatsApp chatbot free no code",
    "WhatsApp no code chatbot",
    "build WhatsApp chatbot free",
    "WhatsApp chatbot for small business",
    "WhatsApp chatbot for India",
    "WhatsApp AI in Hindi",
    "WhatsApp AI Hinglish",
    "WhatsApp Hindi chatbot",
    "WhatsApp 24/7 reply bot",
    "WhatsApp auto reply AI",
    "WhatsApp greeting bot",
    "WhatsApp FAQ bot",
    "WhatsApp helpdesk AI",
    "WhatsApp ticketing AI",
    "WhatsApp human handoff",
    "WhatsApp shared inbox AI",
    "WhatsApp team inbox",
    "WhatsApp CRM",
    "WhatsApp CRM free",
    "WhatsApp lead routing",
    "WhatsApp segmentation AI",
    "WhatsApp drip messaging",
    "WhatsApp re-engagement",
    "WhatsApp cart recovery",
    "WhatsApp abandoned cart bot",
    "Twilio alternative free",
    "Wati alternative free",
    "Interakt alternative free",
    "AiSensy alternative",
    "Gallabox alternative",
    "WhatsApp chatbot vs WATI",
    "best WhatsApp chatbot 2025",
    "best WhatsApp chatbot 2026",
    "best free WhatsApp Business chatbot",
    "WhatsApp chatbot for Shopify",
    "WhatsApp chatbot for WooCommerce",
    "WhatsApp chatbot for restaurants",
    "WhatsApp chatbot for salons",
    "WhatsApp chatbot for real estate",
    "WhatsApp chatbot for clinics",
    "WhatsApp chatbot for tutors",
    "WhatsApp chatbot for boutiques",
    "WhatsApp chatbot for D2C brands",
    "WhatsApp template messages AI",
    "WhatsApp click to chat",
    "WhatsApp QR code AI",
    "WhatsApp opt-in flow",
    "WhatsApp green tick free",
    "WhatsApp Business verified",
    "how to set up WhatsApp chatbot",
    "how to automate WhatsApp replies",
    "how to use WhatsApp Business API for free",
    "WhatsApp chatbot tutorial",
    "WhatsApp AI without coding",
    "WhatsApp AI for India",
    "WhatsApp AI for SMBs",
    "WhatsApp AI for entrepreneurs",
  ],

  inbox: [
    "Inbox AI",
    "AI inbox",
    "AI inbox manager",
    "AI email assistant",
    "AI email manager",
    "AI email triage",
    "AI email summary",
    "AI email digest",
    "AI email sorter",
    "AI email categorization",
    "AI email priority",
    "AI email reply generator",
    "AI email writer",
    "AI auto reply email",
    "AI email automation",
    "Gmail AI",
    "Gmail AI assistant",
    "Gmail AI inbox",
    "Gmail summary AI",
    "Gmail auto reply AI",
    "Outlook AI",
    "Outlook AI assistant",
    "Outlook inbox AI",
    "email AI for Gmail",
    "email AI for Outlook",
    "free Gmail AI",
    "free Outlook AI",
    "free AI email assistant",
    "free email AI",
    "free email triage AI",
    "free Superhuman alternative",
    "free Shortwave alternative",
    "free SaneBox alternative",
    "free Mailbird alternative",
    "Sanebox alternative",
    "Superhuman alternative",
    "Shortwave alternative",
    "Mixmax alternative",
    "Boomerang alternative",
    "Gmail copilot alternative",
    "Outlook copilot alternative",
    "AI inbox zero",
    "inbox zero AI",
    "AI daily email digest",
    "morning email summary AI",
    "7am email briefing",
    "AI sales email AI",
    "AI lead detection email",
    "AI follow up email",
    "AI cold email writer",
    "AI tone matcher email",
    "AI email tone",
    "AI snooze email",
    "AI label email",
    "AI thread summarizer",
    "AI email search",
    "AI email scheduler",
    "AI VIP email",
    "AI unsubscribe assistant",
    "AI bulk email cleanup",
    "AI email cleanup",
    "AI email organizer",
    "AI email focus mode",
    "best free AI email assistant 2025",
    "best free AI email assistant 2026",
    "best Gmail AI 2025",
    "best Outlook AI 2025",
    "AI email for founders",
    "AI email for sales reps",
    "AI email for recruiters",
    "AI email for freelancers",
    "AI email for agencies",
    "AI email for consultants",
    "AI email for executives",
    "how to reach inbox zero with AI",
    "how to summarize emails with AI",
    "how to draft replies with AI",
    "how to triage emails with AI",
    "Gmail AI free no signup",
    "AI inbox India",
    "AI email Hindi",
    "AI email assistant India",
    "AI email triage free",
    "AI email summarizer free",
    "secure AI email assistant",
    "OAuth Gmail AI",
    "OAuth Outlook AI",
  ],

  payables: [
    "Payable AI",
    "AI payables",
    "AI accounts payable",
    "accounts payable automation",
    "AP automation",
    "AP automation free",
    "AI invoice processing",
    "AI invoice automation",
    "AI invoice OCR",
    "invoice OCR AI",
    "invoice scanning AI",
    "invoice extraction AI",
    "invoice data extraction",
    "AI invoice management",
    "AI bill management",
    "AI bill payment",
    "AI bill scheduling",
    "AI vendor management",
    "AI supplier management",
    "AI purchase order",
    "AI PO matching",
    "AI three-way match",
    "AI duplicate invoice detection",
    "AI fraud detection invoices",
    "AI invoice approval workflow",
    "AI invoice routing",
    "AI invoice export Tally",
    "AI invoice export Zoho",
    "AI invoice export QuickBooks",
    "Tally invoice automation AI",
    "Zoho Books invoice AI",
    "QuickBooks invoice AI",
    "Xero invoice AI",
    "free invoice automation",
    "free AP automation",
    "free Bill.com alternative",
    "Bill.com alternative",
    "Stampli alternative",
    "Tipalti alternative",
    "Airbase alternative",
    "Ramp alternative",
    "Brex alternative",
    "Coupa alternative",
    "free Stampli alternative",
    "free Tipalti alternative",
    "AI invoice import Gmail",
    "Gmail invoice extraction AI",
    "AI receipt scanner",
    "AI receipt extraction",
    "AI receipt OCR",
    "AI expense management",
    "AI GST invoice",
    "GST invoice automation",
    "GSTIN extraction AI",
    "HSN code extraction AI",
    "Indian invoice automation",
    "Indian rupee invoice AI",
    "lakhs crores invoice parsing",
    "Indian GST AI",
    "AI accounting India",
    "AP health score",
    "AI cash flow AI",
    "AI vendor scoring",
    "AI vendor risk",
    "AI invoice analytics",
    "best free invoice automation 2025",
    "best free AP automation 2026",
    "AI invoice processing for SMB",
    "AI invoice processing for startups",
    "AI invoice processing for CFOs",
    "AI invoice processing for accountants",
    "AI invoice processing for bookkeepers",
    "AI invoice processing for finance teams",
    "AI invoice processing for retail",
    "AI invoice processing for ecommerce",
    "AI invoice processing for manufacturing",
    "how to automate invoice processing",
    "how to extract invoice data with AI",
    "how to detect duplicate invoices",
    "how to schedule vendor payments",
    "AI invoice for India",
    "AI invoice in Hindi",
    "free AI accounts payable software",
    "free AP software India",
    "AP automation software free",
  ],

  recruit: [
    "Recruit AI",
    "AI recruit",
    "AI hiring",
    "AI hiring software",
    "AI recruiting",
    "AI recruiting software",
    "AI recruiting platform",
    "AI ATS",
    "AI applicant tracking system",
    "applicant tracking system free",
    "free ATS",
    "free ATS software",
    "free ATS for startups",
    "free ATS for small business",
    "AI candidate sourcing",
    "AI candidate screening",
    "AI resume screening",
    "AI resume parser",
    "AI CV parser",
    "AI resume analyzer",
    "AI resume scoring",
    "AI candidate scoring",
    "AI candidate matching",
    "AI job matching",
    "AI interview scheduling",
    "AI interview AI",
    "AI interview assistant",
    "AI interview question generator",
    "AI hiring funnel",
    "AI hiring pipeline",
    "AI hiring workflow",
    "AI offer letter generator",
    "AI rejection email",
    "AI reference check",
    "AI background check",
    "AI hiring analytics",
    "AI talent CRM",
    "AI talent pool",
    "AI recruitment marketing",
    "AI job posting generator",
    "AI JD generator",
    "AI job description writer",
    "AI hiring for startups",
    "AI hiring for SMB",
    "AI hiring for tech",
    "AI hiring for non-tech",
    "AI hiring for agencies",
    "AI hiring for consultants",
    "AI hiring for HR teams",
    "AI hiring for in-house recruiters",
    "AI hiring India",
    "AI recruiting India",
    "Naukri alternative",
    "LinkedIn Recruiter alternative",
    "Greenhouse alternative",
    "Lever alternative",
    "Workable alternative",
    "Recruitee alternative",
    "Zoho Recruit alternative",
    "Freshteam alternative",
    "iSmartRecruit alternative",
    "JazzHR alternative",
    "Manatal alternative",
    "Breezy HR alternative",
    "free Greenhouse alternative",
    "free Lever alternative",
    "free Workable alternative",
    "best free ATS 2025",
    "best free ATS 2026",
    "best AI recruiting tool 2025",
    "best AI hiring tool 2026",
    "AI recruiter assistant",
    "AI recruiter copilot",
    "ChatGPT for recruiters",
    "Gemini for recruiters",
    "AI hiring chatbot",
    "AI candidate chatbot",
    "AI hiring outreach",
    "AI sourcing automation",
    "AI resume database",
    "AI talent database",
    "AI ATS Hindi",
    "AI ATS India",
    "how to screen resumes with AI",
    "how to source candidates with AI",
    "how to schedule interviews with AI",
    "how to write job descriptions with AI",
    "AI hiring software free no signup",
  ],

  ibara: [
    "Ibara",
    "Ibara AI",
    "Ibara widget",
    "Ibara chat widget",
    "Ibara chatbot",
    "Plyndrox Ibara",
    "embeddable AI chatbot",
    "embeddable AI widget",
    "embeddable chatbot",
    "embeddable chat widget",
    "AI chat widget",
    "AI chatbot widget",
    "AI website chatbot",
    "website chatbot",
    "website AI assistant",
    "site chatbot AI",
    "live chat AI",
    "live chat AI free",
    "AI live chat widget",
    "AI customer support widget",
    "AI helpdesk widget",
    "AI knowledge base widget",
    "AI website assistant",
    "AI sales assistant widget",
    "AI lead capture widget",
    "AI booking widget",
    "AI FAQ widget",
    "free AI chatbot for website",
    "free chatbot widget",
    "free embeddable chatbot",
    "free Crisp alternative",
    "free Tidio alternative",
    "free Intercom alternative",
    "free Drift alternative",
    "free Zendesk chat alternative",
    "free LiveChat alternative",
    "Crisp alternative",
    "Tidio alternative",
    "Intercom alternative",
    "Drift alternative",
    "Tawk.to alternative",
    "HubSpot chat alternative",
    "Olark alternative",
    "Freshchat alternative",
    "Botpress alternative",
    "ManyChat alternative",
    "Landbot alternative",
    "Chatbase alternative",
    "AI chatbot for Shopify",
    "AI chatbot for WordPress",
    "AI chatbot for WooCommerce",
    "AI chatbot for Wix",
    "AI chatbot for Squarespace",
    "AI chatbot for Webflow",
    "AI chatbot for Framer",
    "AI chatbot for Carrd",
    "AI chatbot for HTML",
    "AI chatbot for Next.js",
    "AI chatbot for React",
    "AI chatbot script tag",
    "AI chatbot one line install",
    "AI chatbot 60 seconds setup",
    "AI chatbot trained on website",
    "AI chatbot trained on docs",
    "AI chatbot trained on PDF",
    "AI chatbot trained on knowledge base",
    "AI chatbot 100 languages",
    "AI chatbot multilingual",
    "AI chatbot Hindi",
    "AI chatbot India",
    "best free AI chatbot for website 2025",
    "best embeddable AI chatbot 2026",
    "AI chatbot lead generation",
    "AI chatbot capture email",
    "AI chatbot capture phone",
    "AI chatbot meeting booking",
    "AI chatbot Calendly",
    "AI chatbot product demo",
    "AI chatbot for SaaS",
    "AI chatbot for ecommerce store",
    "AI chatbot for agency website",
    "AI chatbot for portfolio",
    "AI chatbot for blog",
    "how to add AI chatbot to website",
    "how to install AI chat widget",
    "how to embed AI chatbot",
    "Ibara vs Intercom",
    "Ibara vs Drift",
    "Ibara vs Crisp",
    "Ibara vs Tidio",
  ],

  bihar: [
    "Bihar AI",
    "Bihar AI assistant",
    "Bihar AI chatbot",
    "Bihar ke liye AI",
    "AI for Bihar",
    "Bihar regional AI",
    "Bihar AI app",
    "Bihari AI",
    "Bhojpuri AI",
    "Bhojpuri AI chatbot",
    "Bhojpuri AI assistant",
    "Maithili AI",
    "Maithili chatbot",
    "Magahi AI",
    "Hindi AI for Bihar",
    "Hindi AI assistant",
    "Hindi AI chatbot",
    "AI in Hindi",
    "Hindi me AI",
    "Hindi me ChatGPT",
    "ChatGPT in Hindi",
    "Hindi GPT",
    "हिंदी AI",
    "हिन्दी एआई",
    "बिहार AI",
    "बिहार के लिए AI",
    "भोजपुरी AI",
    "मैथिली AI",
    "मगही AI",
    "हिंदी चैटबॉट",
    "हिंदी एआई असिस्टेंट",
    "Bihar government schemes AI",
    "Bihar yojana AI",
    "Bihar sarkari yojana AI",
    "Bihar jobs AI",
    "Bihar naukri AI",
    "Bihar sarkari naukri",
    "Bihar education AI",
    "Bihar scholarship AI",
    "Bihar agriculture AI",
    "Bihar krishi AI",
    "Bihar farming AI",
    "Bihar mandi AI",
    "Bihar grain prices AI",
    "Bihar train schedule AI",
    "Bihar railway AI",
    "Bihar weather AI",
    "Bihar mausam AI",
    "Bihar news AI",
    "Bihar samachar AI",
    "Bihar local AI",
    "Bihar district AI",
    "Patna AI",
    "Patna chatbot",
    "Gaya AI",
    "Bhagalpur AI",
    "Muzaffarpur AI",
    "Darbhanga AI",
    "Begusarai AI",
    "AI for rural India",
    "rural AI India",
    "vernacular AI",
    "vernacular AI India",
    "Indic AI",
    "AI for Tier 2 India",
    "AI for Tier 3 India",
    "AI for villages India",
    "AI for farmers India",
    "AI for students Bihar",
    "AI for kisan",
    "AI for chhota vyapari",
    "AI for chhote vyapari",
    "Bihar entrepreneur AI",
    "small business Bihar AI",
    "free Bihar AI",
    "Bihar AI free",
    "best AI for Bihar 2025",
    "best Hindi AI 2025",
    "best Bhojpuri AI 2026",
    "best regional AI India",
    "Bihar startup AI",
    "Bihari startup AI",
    "JEEViKA AI",
    "Bihar Sampark AI",
    "Bihar 1100 AI",
    "Bihar government AI",
    "Bihar e-shikshakosh AI",
    "Bihar civil services AI",
    "BPSC AI",
    "Bihar police AI prep",
    "BSEB AI",
    "Bihar board AI",
    "Hindi medium AI",
    "Hinglish AI Bihar",
  ],

  ledger: [
    "Smart Ledger",
    "Plyndrox Smart Ledger",
    "AI satti",
    "satti AI",
    "satti software",
    "satti software free",
    "satti book AI",
    "satti to digital ledger",
    "satti accounting AI",
    "AI accounting book",
    "AI bahi khata",
    "bahi khata software",
    "digital bahi khata",
    "AI bookkeeping",
    "AI bookkeeping for traders",
    "AI bookkeeping for grain",
    "AI bookkeeping India",
    "free AI bookkeeping",
    "free bookkeeping software",
    "AI ledger software",
    "AI ledger book",
    "ledger book digitization",
    "handwritten ledger OCR",
    "handwritten satti OCR",
    "handwritten ledger AI",
    "handwritten Hindi OCR",
    "Hindi handwriting OCR",
    "Devanagari OCR",
    "Devanagari handwriting AI",
    "AI for grain traders",
    "AI for mandi traders",
    "AI for kirana store",
    "AI for wholesale traders",
    "AI for arhatiya",
    "AI for adhati",
    "AI for commission agent",
    "AI for grain commission agent",
    "AI for godown",
    "AI for warehouse",
    "AI for retail trader",
    "AI for wholesale trader",
    "wholesale trader software AI",
    "kirana shop AI",
    "kirana ledger AI",
    "shopkeeper AI India",
    "small trader AI India",
    "vyapari AI",
    "anaj vyapari AI",
    "anaj mandi AI",
    "krishi mandi AI",
    "mandi rate AI",
    "AI grain rate calculator",
    "AI commission calculator",
    "AI commodity ledger",
    "commodity wise totals AI",
    "Tally alternative free",
    "Vyapar app alternative",
    "Marg ERP alternative",
    "Khatabook alternative",
    "OkCredit alternative",
    "Khata app alternative",
    "AI Khatabook",
    "AI OkCredit",
    "AI digital khata",
    "free Khatabook alternative",
    "AI accounting India free",
    "AI accounting Hindi",
    "AI accounting Bhojpuri",
    "best free accounting software India 2025",
    "best free bookkeeping app India 2026",
    "AI accounting for kisan",
    "AI accounting for farmer",
    "AI accounting for chhote vyapari",
    "AI accounting for rural India",
    "AI ledger PDF export",
    "AI ledger CSV export",
    "AI ledger WhatsApp share",
    "AI ledger summary",
    "AI ledger analytics",
    "AI grain trade analytics",
    "AI grain trade dashboard",
    "AI accounting OCR",
    "Google Vision OCR ledger",
    "Gemini AI ledger",
    "how to digitize satti",
    "how to digitize bahi khata",
    "how to scan handwritten ledger",
    "free ledger software for grain traders",
  ],

  business: [
    "Business AI",
    "Business AI Suite",
    "Business AI platform",
    "Business AI tools",
    "AI for business",
    "AI for businesses",
    "AI for SMB",
    "AI for SME",
    "AI for small business",
    "AI for medium business",
    "AI for enterprise",
    "AI for startups",
    "AI for D2C brands",
    "AI for ecommerce",
    "AI for retail",
    "AI for restaurants",
    "AI for clinics",
    "AI for salons",
    "AI for spas",
    "AI for gyms",
    "AI for coaches",
    "AI for tutors",
    "AI for consultants",
    "AI for agencies",
    "AI for marketing agencies",
    "AI for digital agencies",
    "AI for accountants",
    "AI for CA firms",
    "AI for law firms",
    "AI for real estate",
    "AI for travel agents",
    "AI for event planners",
    "AI for photographers",
    "AI for studios",
    "AI for boutiques",
    "AI for kirana",
    "AI for distributors",
    "AI for wholesalers",
    "AI for manufacturers",
    "AI for exporters",
    "AI for B2B",
    "AI for B2C",
    "AI sales automation",
    "AI marketing automation",
    "AI customer service automation",
    "AI operations automation",
    "AI HR automation",
    "AI finance automation",
    "AI back office automation",
    "all in one AI for business",
    "all-in-one AI suite for business",
    "free AI for business",
    "free AI suite for business",
    "free AI for SMB",
    "free AI for small business",
    "no subscription AI for business",
    "AI suite vs ChatGPT",
    "AI suite vs Gemini",
    "AI suite vs Microsoft Copilot",
    "AI suite for India",
    "AI suite for Indian businesses",
    "AI for Indian SMB",
    "AI for Bharat businesses",
    "ChatGPT for business",
    "Gemini for business",
    "Copilot for business",
    "Anthropic Claude for business",
    "best AI suite 2025",
    "best AI suite 2026",
    "best free AI for business 2025",
    "best free AI tools for SMB 2026",
    "AI for founders",
    "AI for CEOs",
    "AI for entrepreneurs",
    "AI for solopreneurs",
    "AI for freelancers",
    "AI for first time founders",
    "AI for bootstrapped startups",
    "AI ROI",
    "AI cost savings",
    "how to run a business with AI",
    "how to automate a business with AI",
    "how to use AI in small business",
    "how to use AI for sales",
    "how to use AI for marketing",
    "how to use AI for hiring",
    "how to use AI for finance",
    "how to use AI for support",
  ],

  chat: [
    "personal AI",
    "personal AI assistant",
    "personal AI companion",
    "free AI companion",
    "AI companion app",
    "AI friend",
    "AI buddy",
    "AI for thinking",
    "AI for journaling",
    "AI journaling assistant",
    "AI for self reflection",
    "AI for mental wellness",
    "AI mental health companion",
    "AI emotional support",
    "AI emotional companion",
    "AI for loneliness",
    "AI for anxiety support",
    "AI for stress relief",
    "AI for mindfulness",
    "AI therapist alternative",
    "AI therapist free",
    "AI counsellor alternative",
    "Replika alternative",
    "Pi AI alternative",
    "Character.AI alternative",
    "Inflection Pi alternative",
    "Wysa alternative",
    "Woebot alternative",
    "free Replika alternative",
    "free Character.AI alternative",
    "free Pi AI alternative",
    "free ChatGPT alternative",
    "ChatGPT alternative no signup",
    "free ChatGPT no signup",
    "AI chat no signup",
    "AI chat without account",
    "free AI chatbot online",
    "free AI assistant online",
    "AI for daily planning",
    "AI day planner",
    "AI weekly planner",
    "AI to-do list",
    "AI productivity coach",
    "AI life coach",
    "AI study buddy",
    "AI study assistant",
    "AI study companion",
    "AI homework helper",
    "AI tutor",
    "AI tutor for English",
    "AI tutor for Hindi",
    "AI tutor for math",
    "AI for learning",
    "AI for self improvement",
    "AI for personal growth",
    "AI for habit tracking",
    "AI habit coach",
    "AI for parenting",
    "AI for relationships",
    "AI for career advice",
    "AI for resume writing",
    "AI for interview prep",
    "AI for English speaking",
    "AI for spoken English",
    "AI English coach",
    "AI English tutor India",
    "AI for Indian students",
    "AI for Bihar students",
    "AI in Hinglish",
    "AI Hinglish chatbot",
    "AI for daily journaling Hindi",
    "free AI in Hindi",
    "free AI in Hinglish",
    "best free AI companion 2025",
    "best AI chat 2026",
    "best AI assistant for India 2025",
    "AI chat private",
    "AI chat secure",
    "AI chat encrypted",
    "AI chat without ads",
    "AI for thinking out loud",
    "AI for brainstorming",
    "AI for creative writing",
    "AI for poetry",
    "AI for songwriting",
    "AI for ideation",
  ],

  translate: [
    "AI translator",
    "AI translation",
    "AI translation app",
    "AI translation tool",
    "AI translation software",
    "AI translator online",
    "AI translator free",
    "free AI translator",
    "free translator",
    "free translator no signup",
    "translator no signup",
    "Google Translate alternative",
    "DeepL alternative",
    "Microsoft Translator alternative",
    "Reverso alternative",
    "free DeepL alternative",
    "free Google Translate alternative",
    "neural translator",
    "human translator AI",
    "natural translator AI",
    "context aware translator",
    "AI translator with context",
    "translator with grammar fix",
    "translator with auto correct",
    "translator with explanation",
    "translator with examples",
    "translator with notes",
    "translator pronunciation AI",
    "translate 100 languages",
    "translator 100 languages",
    "translator for 100 languages",
    "translator multilingual",
    "AI translator multilingual",
    "translate Hindi to English",
    "translate English to Hindi",
    "translate Bhojpuri to English",
    "translate English to Bhojpuri",
    "translate Hinglish to English",
    "translate Marathi to English",
    "translate Tamil to English",
    "translate Telugu to English",
    "translate Bengali to English",
    "translate Punjabi to English",
    "translate Gujarati to English",
    "translate Kannada to English",
    "translate Malayalam to English",
    "translate Urdu to English",
    "translate Sanskrit to English",
    "translate Maithili to English",
    "translate Magahi to English",
    "translate Spanish to English",
    "translate French to English",
    "translate German to English",
    "translate Mandarin to English",
    "translate Arabic to English",
    "translate Japanese to English",
    "translate Korean to English",
    "translate Portuguese to English",
    "translate Russian to English",
    "translate Indonesian to English",
    "translate Vietnamese to English",
    "translate Thai to English",
    "translate Turkish to English",
    "translate Swahili to English",
    "Indian language translator AI",
    "Indic language translator",
    "Indic AI translator",
    "AI translator India",
    "AI translator Hindi",
    "AI translator Hinglish",
    "AI translator no chat history",
    "private AI translator",
    "secure AI translator",
    "AI translator for students",
    "AI translator for travelers",
    "AI translator for business",
    "AI translator for emails",
    "AI translator for documents",
    "AI translator for messages",
    "AI translator for WhatsApp",
    "AI translator for chat",
    "AI translator with typo fix",
    "translate text AI free",
    "translate paragraph AI",
    "translate sentence AI",
    "AI translation in Hindi",
    "AI translation Bhojpuri",
    "best free AI translator 2025",
    "best AI translator 2026",
    "best Hindi translator AI",
    "best Indian translator AI",
    "how to translate with AI",
    "how to translate Hindi to English with AI",
  ],

  features: [
    "Plyndrox features",
    "Plyndrox AI features",
    "Plyndrox capabilities",
    "AI suite features",
    "all in one AI features",
    "free AI features",
    "AI platform features",
    "AI platform capabilities",
    "AI features for business",
    "AI features for SMB",
    "AI features for personal use",
    "AI features comparison",
    "AI features list",
    "what does Plyndrox do",
    "what is Plyndrox AI",
    "Plyndrox vs ChatGPT",
    "Plyndrox vs Gemini",
    "Plyndrox vs Claude",
    "Plyndrox vs Copilot",
    "Plyndrox vs Perplexity",
    "Plyndrox review",
    "Plyndrox AI review",
    "Plyndrox demo",
    "Plyndrox use cases",
    "free AI feature comparison",
  ],

  pricing: [
    "Plyndrox pricing",
    "Plyndrox AI pricing",
    "Plyndrox cost",
    "Plyndrox AI cost",
    "Plyndrox free plan",
    "Plyndrox subscription",
    "Plyndrox business plan",
    "Plyndrox enterprise plan",
    "free AI pricing",
    "is Plyndrox free",
    "is Plyndrox AI really free",
    "Plyndrox free forever",
    "Plyndrox free for business",
    "Plyndrox free for personal use",
    "free AI tools pricing",
    "free AI subscription",
    "free AI no credit card",
    "free AI no signup",
    "AI without subscription",
    "AI without paywall",
    "ChatGPT pricing alternative",
    "Gemini pricing alternative",
    "Copilot pricing alternative",
    "best free AI 2025",
    "best free AI 2026",
    "best free AI no credit card",
  ],

  solutions: [
    "Plyndrox solutions",
    "AI solutions",
    "AI solutions by industry",
    "AI for restaurants",
    "AI for cafes",
    "AI for cloud kitchens",
    "AI for ecommerce stores",
    "AI for D2C brands",
    "AI for online stores",
    "AI for Shopify stores",
    "AI for Amazon sellers",
    "AI for Flipkart sellers",
    "AI for real estate agents",
    "AI for real estate brokers",
    "AI for property dealers",
    "AI for clinics",
    "AI for hospitals",
    "AI for doctors",
    "AI for dentists",
    "AI for spas",
    "AI for salons",
    "AI for beauty parlours",
    "AI for gyms",
    "AI for fitness coaches",
    "AI for personal trainers",
    "AI for yoga instructors",
    "AI for tutors",
    "AI for online tutors",
    "AI for coaching institutes",
    "AI for ed-tech",
    "AI for travel agents",
    "AI for tour operators",
    "AI for event planners",
    "AI for wedding planners",
    "AI for photographers",
    "AI for boutiques",
    "AI for tailors",
    "AI for jewellery shops",
    "AI for grocery stores",
    "AI for kirana stores",
    "AI for chemists",
    "AI for pharmacies",
    "AI for general stores",
    "AI for distributors",
    "AI for wholesalers",
    "AI for manufacturers",
    "AI for exporters",
    "AI for importers",
    "AI for digital agencies",
    "AI for marketing agencies",
    "AI for SEO agencies",
    "AI for design agencies",
    "AI for content creators",
    "AI for influencers",
    "AI for YouTubers",
    "AI for podcasters",
    "AI for newsletter writers",
    "AI for solopreneurs",
    "AI for freelancers",
    "AI for consultants",
    "AI for coaches",
    "AI for accountants",
    "AI for CAs",
    "AI for tax consultants",
    "AI for bookkeepers",
    "AI for HR teams",
    "AI for recruiters",
    "AI for sales teams",
    "AI for support teams",
    "AI for operations teams",
    "AI for finance teams",
    "AI for marketing teams",
    "AI for product teams",
    "AI for engineering teams",
    "AI for non-profits",
    "AI for NGOs",
    "AI for government",
    "AI for cooperatives",
    "AI for SHGs",
    "AI for FPOs",
    "AI for kisan",
    "AI for farmers",
    "AI for rural India",
    "AI for tier 2 cities",
    "AI for tier 3 cities",
  ],
} as const;

export type ProductKeywordSet = keyof typeof productKeywords;

type BuildMetadataInput = {
  title: string;
  description: string;
  path: string;
  keywords?: string[];
  ogImage?: string;
  ogType?: "website" | "article" | "profile";
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
  noIndex?: boolean;
  alternateLanguages?: Record<string, string>;
};

export function buildMetadata({
  title,
  description,
  path,
  keywords,
  ogImage = "/opengraph-image",
  ogType = "website",
  publishedTime,
  modifiedTime,
  authors,
  noIndex,
  alternateLanguages,
}: BuildMetadataInput): Metadata {
  const fullTitle = title.includes("Plyndrox") ? title : `${title} | Plyndrox AI`;
  const url = path.startsWith("http") ? path : `${SITE_URL}${path}`;
  const seen = new Set<string>();
  const dedupedKeywords: string[] = [];
  for (const kw of [...siteConfig.defaultKeywords, ...(keywords ?? [])]) {
    const key = kw.toLowerCase().trim();
    if (key && !seen.has(key)) {
      seen.add(key);
      dedupedKeywords.push(kw);
    }
  }
  const finalKeywords = dedupedKeywords.join(", ");

  return {
    title: fullTitle,
    description,
    keywords: finalKeywords,
    alternates: {
      canonical: url,
      languages: {
        "x-default": url,
        en: url,
        ...(alternateLanguages ?? {}),
      },
      types: {
        "application/rss+xml": [{ url: `${SITE_URL}/feed.xml`, title: "Plyndrox AI Blog RSS" }],
      },
    },
    robots: noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
          },
        },
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      type: ogType,
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      ...(publishedTime ? { publishedTime } : {}),
      ...(modifiedTime ? { modifiedTime } : {}),
      ...(authors && ogType === "article" ? { authors } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      site: siteConfig.twitterHandle,
      creator: siteConfig.twitterHandle,
      images: [ogImage],
    },
  };
}

export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${SITE_URL}#organization`,
    name: siteConfig.organization.legalName,
    alternateName: [siteConfig.shortName, "Plyndrox", "Plyndrox AI Platform"],
    url: SITE_URL,
    logo: {
      "@type": "ImageObject",
      url: `${SITE_URL}/icons/plyndrox-512.png`,
      width: 512,
      height: 512,
    },
    image: `${SITE_URL}/opengraph-image`,
    foundingDate: siteConfig.organization.foundingDate,
    foundingLocation: {
      "@type": "Place",
      name: siteConfig.organization.foundingLocation,
    },
    email: siteConfig.organization.email,
    slogan: siteConfig.slogan,
    description: siteConfig.defaultDescription,
    sameAs: siteConfig.organization.sameAs,
    knowsAbout: siteConfig.organization.knowsAbout,
    areaServed: [
      { "@type": "Country", name: "India" },
      { "@type": "Country", name: "United States" },
      { "@type": "Country", name: "United Kingdom" },
      { "@type": "Country", name: "Worldwide" },
    ],
    contactPoint: [
      {
        "@type": "ContactPoint",
        contactType: "customer support",
        email: siteConfig.organization.contactEmail,
        availableLanguage: ["English", "Hindi", "Bhojpuri", "Maithili", "Spanish"],
        areaServed: "Worldwide",
      },
      {
        "@type": "ContactPoint",
        contactType: "sales",
        email: siteConfig.organization.salesEmail,
        availableLanguage: ["English", "Hindi"],
      },
      {
        "@type": "ContactPoint",
        contactType: "press",
        email: siteConfig.organization.pressEmail,
        availableLanguage: ["English"],
      },
    ],
  };
}

export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE_URL}#website`,
    name: siteConfig.name,
    alternateName: siteConfig.shortName,
    url: SITE_URL,
    description: siteConfig.defaultDescription,
    inLanguage: ["en", "hi"],
    publisher: { "@id": `${SITE_URL}#organization` },
    potentialAction: [
      {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${SITE_URL}/blog?q={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    ],
  };
}

export function softwareApplicationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "@id": `${SITE_URL}#software`,
    name: siteConfig.name,
    operatingSystem: "Web, iOS, Android",
    applicationCategory: "BusinessApplication",
    applicationSubCategory: "Artificial Intelligence Platform",
    description: siteConfig.defaultDescription,
    url: SITE_URL,
    image: `${SITE_URL}/icons/plyndrox-512.png`,
    softwareVersion: "1.0",
    inLanguage: ["en", "hi"],
    featureList: [
      "Personal AI companion (Simi & Loa)",
      "WhatsApp AI customer automation",
      "Inbox AI for Gmail and Outlook",
      "Payable AI invoice automation",
      "Recruit AI applicant tracking system",
      "Bihar AI regional assistant",
      "Smart Ledger handwritten accounting",
      "Ibara embeddable chat widget",
    ],
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      priceValidUntil: "2030-12-31",
    },
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "4.9",
      ratingCount: "1280",
      reviewCount: "1280",
      bestRating: "5",
      worstRating: "1",
    },
    publisher: { "@id": `${SITE_URL}#organization` },
  };
}

export function breadcrumbJsonLd(items: { name: string; url: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, idx) => ({
      "@type": "ListItem",
      position: idx + 1,
      name: item.name,
      item: item.url.startsWith("http") ? item.url : `${SITE_URL}${item.url}`,
    })),
  };
}

export function faqJsonLd(items: { question: string; answer: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };
}

export function articleJsonLd(opts: {
  title: string;
  description: string;
  slug: string;
  publishedAt: string;
  modifiedAt?: string;
  author: string;
  image?: string;
  category?: string;
  tags?: string[];
}) {
  const url = `${SITE_URL}/blog/${opts.slug}`;
  return {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: opts.title,
    description: opts.description,
    image: opts.image
      ? opts.image.startsWith("http")
        ? opts.image
        : `${SITE_URL}${opts.image}`
      : `${SITE_URL}/opengraph-image`,
    datePublished: opts.publishedAt,
    dateModified: opts.modifiedAt ?? opts.publishedAt,
    author: {
      "@type": "Person",
      name: opts.author,
      url: `${SITE_URL}/about`,
    },
    publisher: { "@id": `${SITE_URL}#organization` },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": url,
    },
    url,
    isPartOf: { "@id": `${SITE_URL}/blog#blog` },
    inLanguage: "en",
    articleSection: opts.category,
    keywords: opts.tags?.join(", "),
    speakable: {
      "@type": "SpeakableSpecification",
      cssSelector: ["h1", "article p"],
    },
  };
}

/**
 * Per-product SoftwareApplication schema. Use inside each product's layout.tsx
 * so search engines can present each Plyndrox product as its own entity with
 * its own rating, price, and feature list.
 */
export function productAppJsonLd(opts: {
  id: string;
  name: string;
  url: string;
  description: string;
  category?: string;
  subCategory?: string;
  features?: string[];
  rating?: { value: string; count: string };
  image?: string;
  inLanguage?: string[];
}) {
  const url = opts.url.startsWith("http") ? opts.url : `${SITE_URL}${opts.url}`;
  const image = opts.image
    ? opts.image.startsWith("http")
      ? opts.image
      : `${SITE_URL}${opts.image}`
    : `${SITE_URL}/opengraph-image`;
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "@id": `${url}#software`,
    name: opts.name,
    url,
    description: opts.description,
    image,
    applicationCategory: opts.category ?? "BusinessApplication",
    applicationSubCategory: opts.subCategory ?? "Artificial Intelligence",
    operatingSystem: "Web, iOS, Android",
    inLanguage: opts.inLanguage ?? ["en", "hi"],
    featureList: opts.features ?? [],
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
    },
    ...(opts.rating
      ? {
          aggregateRating: {
            "@type": "AggregateRating",
            ratingValue: opts.rating.value,
            ratingCount: opts.rating.count,
            reviewCount: opts.rating.count,
            bestRating: "5",
            worstRating: "1",
          },
        }
      : {}),
    publisher: { "@id": `${SITE_URL}#organization` },
    isPartOf: { "@id": `${SITE_URL}#software` },
  };
}

export function webPageJsonLd(opts: {
  url: string;
  name: string;
  description: string;
  breadcrumb?: { name: string; url: string }[];
  speakable?: boolean;
  primaryImage?: string;
}) {
  const url = opts.url.startsWith("http") ? opts.url : `${SITE_URL}${opts.url}`;
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": `${url}#webpage`,
    url,
    name: opts.name,
    description: opts.description,
    isPartOf: { "@id": `${SITE_URL}#website` },
    inLanguage: "en",
    primaryImageOfPage: opts.primaryImage
      ? {
          "@type": "ImageObject",
          url: opts.primaryImage.startsWith("http")
            ? opts.primaryImage
            : `${SITE_URL}${opts.primaryImage}`,
        }
      : undefined,
    ...(opts.speakable
      ? {
          speakable: {
            "@type": "SpeakableSpecification",
            cssSelector: ["h1", "h2", "main p"],
          },
        }
      : {}),
    ...(opts.breadcrumb
      ? {
          breadcrumb: breadcrumbJsonLd(opts.breadcrumb),
        }
      : {}),
  };
}

export function itemListJsonLd(opts: {
  name: string;
  items: { name: string; url: string; description?: string; image?: string }[];
}) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: opts.name,
    numberOfItems: opts.items.length,
    itemListOrder: "https://schema.org/ItemListOrderAscending",
    itemListElement: opts.items.map((item, idx) => ({
      "@type": "ListItem",
      position: idx + 1,
      url: item.url.startsWith("http") ? item.url : `${SITE_URL}${item.url}`,
      name: item.name,
      ...(item.description ? { description: item.description } : {}),
      ...(item.image
        ? {
            image: item.image.startsWith("http") ? item.image : `${SITE_URL}${item.image}`,
          }
        : {}),
    })),
  };
}

export function collectionPageJsonLd(opts: {
  url: string;
  name: string;
  description: string;
  itemList?: ReturnType<typeof itemListJsonLd>;
}) {
  const url = opts.url.startsWith("http") ? opts.url : `${SITE_URL}${opts.url}`;
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "@id": `${url}#collection`,
    url,
    name: opts.name,
    description: opts.description,
    isPartOf: { "@id": `${SITE_URL}#website` },
    inLanguage: "en",
    publisher: { "@id": `${SITE_URL}#organization` },
    ...(opts.itemList ? { mainEntity: opts.itemList } : {}),
  };
}

export function serviceJsonLd(opts: {
  name: string;
  url: string;
  description: string;
  serviceType: string;
  areaServed?: string[];
}) {
  const url = opts.url.startsWith("http") ? opts.url : `${SITE_URL}${opts.url}`;
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name: opts.name,
    url,
    description: opts.description,
    serviceType: opts.serviceType,
    provider: { "@id": `${SITE_URL}#organization` },
    areaServed: (opts.areaServed ?? ["Worldwide"]).map((a) => ({
      "@type": "Place",
      name: a,
    })),
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
    },
  };
}

export function howToJsonLd(opts: {
  name: string;
  description: string;
  steps: { name: string; text: string; url?: string }[];
  totalTime?: string;
  image?: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: opts.name,
    description: opts.description,
    ...(opts.totalTime ? { totalTime: opts.totalTime } : {}),
    ...(opts.image
      ? {
          image: opts.image.startsWith("http") ? opts.image : `${SITE_URL}${opts.image}`,
        }
      : {}),
    step: opts.steps.map((s, idx) => ({
      "@type": "HowToStep",
      position: idx + 1,
      name: s.name,
      text: s.text,
      ...(s.url
        ? {
            url: s.url.startsWith("http") ? s.url : `${SITE_URL}${s.url}`,
          }
        : {}),
    })),
  };
}
